// frontend-react/src/components/UserList.js
import React from 'react';
import PropTypes from 'prop-types';

const UserList = ({
    users,
    setSelectedUser,
    setIsCreateOrEditUserDialogOpen,
    setIsDeleteDialogOpen,
    page
}) => {
    const edit = user => {
        setSelectedUser(user);
        setIsCreateOrEditUserDialogOpen(true);
    };

    const destroy = user => {
        setSelectedUser(user);
        setIsDeleteDialogOpen(true);
    };

    return (
        <div className="px-4 sm:px-6 lg:px-8">
            <div className="-mx-4 mt-8 overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:-mx-6 md:mx-0 md:rounded-lg">
                <table className="min-w-full divide-y divide-gray-300">
                    <thead className="bg-gray-50">
                        <tr>
                            <th
                                scope="col"
                                className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"
                            >
                                First name
                            </th>
                            <th
                                scope="col"
                                className="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6"
                            >
                                Last name
                            </th>
                            <th
                                scope="col"
                                className="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 lg:table-cell"
                            >
                                Email
                            </th>
                            <th
                                scope="col"
                                className="hidden px-3 py-3.5 text-left text-sm font-semibold text-gray-900 sm:table-cell"
                            >
                                Date of birth
                            </th>
                            <th
                                scope="col"
                                className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                            >
                                Vacation days total
                            </th>
                            <th
                                scope="col"
                                className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                            >
                                Vacation days taken
                            </th>
                            <th
                                scope="col"
                                className="px-3 py-3.5 text-left text-sm font-semibold text-gray-900"
                            >
                                Actions
                            </th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-200 bg-white">
                        {users[page]?.map(user => (
                            <tr key={user.id}>
                                <td className="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none sm:pl-6">
                                    {user.firstName}
                                </td>
                                <td className="w-full max-w-0 py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:w-auto sm:max-w-none sm:pl-6">
                                    {user.lastName}
                                </td>
                                <td className="hidden px-3 py-4 text-sm text-gray-500 lg:table-cell">
                                    {user.email}
                                </td>
                                <td className="hidden px-3 py-4 text-sm text-gray-500 sm:table-cell">
                                    {user.birthDate}
                                </td>
                                <td className="px-3 py-4 text-sm text-gray-500">
                                    {user.vacationDaysTotal}
                                </td>
                                <td className="px-3 py-4 text-sm text-gray-500">
                                    {user.vacationDaysTaken}
                                </td>
                                <td className="px-3 py-4 text-sm text-gray-500">
                                    <button
                                        className="bg-blue-900 hover:bg-gray-800 text-white h-6 w-16 rounded-lg font-semibold mr-4"
                                        onClick={() => edit(user)}
                                    >
                                        EDIT
                                    </button>
                                    <button
                                        className="bg-red-500 hover:bg-gray-800 text-white h-6 w-20 rounded-lg font-semibold"
                                        onClick={() => destroy(user)}
                                    >
                                        DELETE
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

UserList.propTypes = {
    users: PropTypes.array,
    setSelectedUser: PropTypes.func,
    setIsCreateOrEditUserDialogOpen: PropTypes.func,
    setIsDeleteDialogOpen: PropTypes.func,
    page: PropTypes.number
};

export default UserList;

// client-ssr/components/users/UserList.vue
<template>
    <v-data-table
        class="elevation-2 mt-5"
        :options.sync="tableOptions"
        :page="page"
        :headers="headers"
        :items="users"
        :items-per-page="10"
        :footer-props="{
            itemsPerPageOptions: [10, 25, 50]
        }"
        :server-items-length="count"
    >
        <template v-slot:[`item.action`]="{ item }">
            <v-icon
                v-if="actions.edit"
                small
                class="mr-2"
                color="blue-grey lighten-5"
                @click="$emit('edit', item)"
            >
                mdi-pencil
            </v-icon>
            <v-icon
                v-if="actions.delete"
                small
                class="mr-2"
                color="red"
                @click="$emit('delete', item)"
            >
                mdi-delete
            </v-icon>
        </template>
    </v-data-table>
</template>

<script>
export default {
    props: {
        actions: {
            type: Object,
            default: () => ({
                actions: {
                    edit: true,
                    delete: true
                }
            })
        },
        users: {
            type: Array,
            required: false,
            default: () => []
        },
        count: {
            type: Number,
            required: false,
            default: 0
        },
        page: {
            type: Number,
            required: false,
            default: 1
        }
    },
    data() {
        return {
            headers: [
                {
                    text: 'ID',
                    value: 'id',
                    sortable: false
                },
                {
                    text: 'First name',
                    value: 'firstName',
                    sortable: false
                },
                {
                    text: 'Last name',
                    value: 'lastName',
                    sortable: false
                },
                {
                    text: 'Email',
                    value: 'email',
                    sortable: false
                },
                {
                    text: 'Date of birth',
                    value: 'birthDate',
                    sortable: false
                },
                {
                    text: 'Vacation days total',
                    value: 'vacationDaysTotal',
                    sortable: false,
                    align: 'center'
                },
                {
                    text: 'Vacation days taken',
                    value: 'vacationDaysTaken',
                    sortable: false,
                    align: 'center'
                },
                {
                    text: 'Actions',
                    value: 'action',
                    sortable: false,
                    align: 'center'
                }
            ],
            showCreateOrEditModal: false,
            tableOptions: {}
        };
    },

    watch: {
        tableOptions: {
            handler(options) {
                this.$emit('update-table', options);
            },
            deep: true
        }
    }
};
</script>
